### ISSUE TITLE
use os.linesep for line separation for compatibility with non-windows systems

### ISSUE THREAD

**Issue by chaotika** [vonshednob/pytodotxt#3]
line 64 in todotxt.py uses a hard coded line ending with windows encoding which causes problems on linux when checking in files with git.

**Comment by vonshednob** [comment]
Thanks a lot for raising this issue - and fixing it :grin:

I was actually considering that for some time. Unfortunately the specs for todo.txt do not quite specify the line ending, which is why I fell back to use `\r\n`.

Do you think it would make sense to detect the line ending of the file, remember it and re-use it rather than using the system default?
I'm thinking of cases where a group of people are using the same todo.txt file synchronised between multiple systems (e.g. Windows and Linux).

What do you think?

**Comment by chaotika** [comment]
Yeah that would be ideal. I think since the todo.txt format is defined as storing stuff  in a text file it assumes that you use the respective system line endings here. I know git has some way to autoconvert but i use only linux so i did not have to deal with issues here a lot.

**Comment by chaotika** [comment]
Also i was thinking that one solution might be to specify some option to be able to set the line ending format and default to os.linesep.

**Comment by vonshednob** [comment]
Thanks a lot, @chaotika for fixing it!

4fb131cf11e7c3f56aba7c9660416892c41f5a4b
